micropost:
  content:
    max_length: 140
  picture_size: 5
user:
  name:
    max_length: 255
  email:
    max_length: 255
  expired_time: 2
  password:
    min_length: 6
user_helper:
  gravatar:
    size: 80
users:
  index:
    per_page: 10
  user:
    size: 50
picture:
  limit_size:
    height: 200
    width: 200
